#!/usr/bin/env bash
# Commands used to configure ufw on web-01: deny all incoming traffic except SSH, HTTP, and HTTPS

sudo apt update
sudo apt install -y ufw

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

sudo ufw default deny incoming
sudo ufw enable
