#!/usr/bin/env bash
# Install nginx web server
# Install the Nginx server silently
apt update -y > /dev/null 2>&1
apt install nginx -y > /dev/null 2>&1
# This overwrites the default page with my message
rm -f /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" | tee /var/www/html/index.html > /dev/null
# Restart server
service nginx restart > /dev/null 2>&1
